# Generated by Django 5.0.4 on 2024-04-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_clothes_name_alter_clothes_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='clothes.category'),
        ),
    ]
