# Generated by Django 5.0.4 on 2024-04-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothes_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.AlterModelTable(
            name='clothes',
            table='clothes',
        ),
    ]
