# Generated by Django 5.0.4 on 2024-04-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_clothes_options_alter_clothes_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={},
        ),
        migrations.AlterModelTable(
            name='clothes',
            table=None,
        ),
    ]
