# Generated by Django 5.0.4 on 2024-04-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_clothes_options_alter_clothes_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothes',
            new_name='Cloth',
        ),
    ]
