# Generated by Django 5.0.4 on 2024-04-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_clothes_delete_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(),
        ),
    ]
